spring:
  ### Profile ###
  profiles: 
    active: local
  ### General Information ###
  application:
    name: autoscaler-dev
  ### Security ###
  ssl:
    acceptSelfSigned: true
  ### Cloud Config ###
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

  ### General Information ###
  info:
    app:
      name: Autoscaler Service Broker
      description: This is a Autoscaler Service Broker
      version: 1.1.0

  server:
    port: 8080