spring:
  ### Profile ###
  profiles: 
    active: local
  ### General Information ###
  application:
    name: autoscaler-dev
  ### Security ###
  ssl:
    acceptSelfSigned: true
  ### Cloud Config ###
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

  ### General Information ###
  info:
    app:
      name: Autoscaler Service Broker
      description: This is a Autoscaler Service Broker
      version: 1.1.0

  server:
    port: 8080
  rabbitmq:
    host: "${RABBITMQ_HOST}"
  data:
    mongodb:
      host: "${MONGODB_HOST}"
haproxy:
  uri: "https://${SERVICE_KEY_MANAGER}/agents/${HAPROXY_AGENT_ID}/schemas?type=listen"
existing:
  endpoint:
    pcfHosts: "${HAPROXY_HOSTS}"
    name: haproxy
    port: 3306
